### ISSUE TITLE
iotile shell quits when there is no matching quotation on a line

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#140]
Error thrown is:
```
(SensorGraph) input 'input 5
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Arch\env\firmware-dev\Scripts\iotile.exe\__main__.py", line 9, in <module>
  File "c:\arch\env\firmware-dev\lib\site-packages\iotile\core\scripts\iotile_script.py", line 110, in main
    line = shlex.split(linebuf, posix=posix_lex)
  File "c:\python27\Lib\shlex.py", line 279, in split
    return list(lex)
  File "c:\python27\Lib\shlex.py", line 269, in next
    token = self.get_token()
  File "c:\python27\Lib\shlex.py", line 96, in get_token
    raw = self.read_token()
  File "c:\python27\Lib\shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
```

Expected behavior: shell should raise an iotile exception and not close the entire program.

**Comment by mattrunchey** [comment]
In #940  it looks like the behavior here is fixed
