### ISSUE TITLE
Hang in BLED112 on_disconnect

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#212]
Log Trace

```
Jun 02 19:19:26 localhost gateway.sh[10352]: Traceback (most recent call last):
Jun 02 19:19:26 localhost gateway.sh[10352]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Jun 02 19:19:26 localhost gateway.sh[10352]: self.run()
Jun 02 19:19:26 localhost gateway.sh[10352]: File "/config/gateway/venv/local/lib/python2.7/site-packages/iotile_transport_bled112/bled112_cmd.py", line 73, in run
Jun 02 19:19:26 localhost gateway.sh[10352]: callback(result_obj)
Jun 02 19:19:26 localhost gateway.sh[10352]: File "/config/gateway/venv/local/lib/python2.7/site-packages/iotile_transport_bled112/bled112.py", line 629, in _on_disconnect
Jun 02 19:19:26 localhost gateway.sh[10352]: del self._connections[handle] #NB Cleanup connection after callback in case it needs the connection info
Jun 02 19:19:26 localhost gateway.sh[10352]: KeyError: 0
Jun 02 19:19:26 localhost gateway.sh[10352]: I-2017-06-02 19:19:26,740-wshandler :130  Client disconnected
Jun 02 19:19:27 localhost gateway.sh[10352]: I-2017-06-02 19:19:27,537-bled112   :811  Restarting scan for devices
```

**Comment by diametralpitch** [comment]
addressed in PR https://github.com/iotile/coretools/pull/214

**Comment by diametralpitch** [comment]
fixed in release https://github.com/iotile/coretools/tree/iotile_transport_bled112-1.4.5
