### ISSUE TITLE
iotile-build - Unable to merge connrf52832_nrf52832_v2.elf and execnrf52832_nrf52832_v2.elf

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#360]
```
scons: *** [build\output\test_final.hex] AddressOverlapError : Starting addresses are different
Traceback (most recent call last):
  File "c:\users\chris\iotile\env\iotile-dev\lib\site-packages\iotile\build\config\scons-local-2.5.1\SCons\Action.py", line 1054, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "c:\users\chris\iotile\env\iotile-dev\lib\site-packages\iotile\build\config\site_scons\arm.py", line 358, in merge_hex_executables
    hex_final.merge(hex_data, overlap='error')
  File "c:\users\chris\iotile\coretools\iotilecore\iotile\core\utilities\intelhex\__init__.py", line 880, in merge
    'Starting addresses are different')
AddressOverlapError: Starting addresses are different
```

No segments are overlapping, but it looks like CS and IP values are different, which causes the error to be thrown when merging hex files

**Comment by x24ling** [comment]
https://stackoverflow.com/questions/26295776/what-are-the-intel-hex-records-type-03-or-05-doing-in-ihex-program-for-arm

Looks like CS and IP not needed, will be setting them to None before merging.
