### ISSUE TITLE
Cannot Ctrl-C from a Mac to kill watch_broadcast

### ISSUE THREAD

**Issue by dkarchmer** [iotile/coretools#486]
Every time I run

```
iotile config set bled112:active-scan true
iotile hw enable broadcasting watch_broadcast
```

And then try to `Ctrl-C` from my Mac, I get locked, and I have to kill my terminal. Many times, that will also corrupt my BLE112 dongle connection, so I have to disconnect and reconnect.

Anyway, this is the error I get before it locked out:

```
(iotile) arch-david1:iotile-smart-edge david$ iotile hw enable_broadcasting watch_broadcasts
Traceback (most recent call last):
  File "/Users/david/.virtualenv/iotile/bin/iotile", line 11, in <module>
    sys.exit(main())
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/iotile/core/scripts/iotile_script.py", line 208, in main
    finished = shell.invoke(line)
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/typedargs/shell.py", line 494, in invoke
    val, line, finished = self.invoke_one(line)
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/typedargs/shell.py", line 457, in invoke_one
    val = func(*posargs, **kwargs)
  File "<decorator-gen-19>", line 2, in watch_broadcasts
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/typedargs/utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/iotile/core/hw/hwmanager.py", line 486, in watch_broadcasts
    line_ui.run()
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/iotile/core/utilities/linebuffer_ui.py", line 70, in run
    Screen.wrapper(self._run_loop, arguments=[refresh_interval])
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/asciimatics/screen.py", line 1167, in wrapper
    func(screen, *arguments)
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/iotile/core/utilities/linebuffer_ui.py", line 91, in _run_loop
    screen.clear()
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/asciimatics/screen.py", line 1230, in clear
    self.reset()
  File "/Users/david/.virtualenv/iotile/lib/python2.7/site-packages/asciimatics/screen.py", line 360, in reset
    json.loads(json.dumps(line)) for _ in range(self._buffer_height)]
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
KeyboardInterrupt
```

**Comment by x24ling** [comment]
Does the same for me on windows
