### ISSUE TITLE
IndexError after scan sometimes?

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#520]
Possibly an issue with my bluetooth connector, but opening this to track and see if anyone else has the issue. Would probably be a good idea to handle this exception, give user description of event (or put in a debug log) and recover, because this error seems to cause the bled112 adapter to hang (that is, i'm unable to 'quit' because it waits for an event forever and ctrl-c is required to close the program).

```
(HardwareManager) Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 38, in run
    self._process_events()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 766, in _process_events
    self.event_handler(event)
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 447, in _handle_event
    self._parse_scan_response(event)
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 530, in _parse_scan_response
    if (scan_data[3] == 17 and
IndexError: bytearray index out of range
```

And then when doing quit, and waiting for 30 seconds, followed by ctrl-c (twice, :
```
(HardwareManager) quit
^CTraceback (most recent call last):
  File "/Users/mrunchey/ota_dev/bin/iotile", line 11, in <module>
    load_entry_point('iotile-core', 'console_scripts', 'iotile')()
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/scripts/iotile_script.py", line 267, in main
    cmdstream.do_final_close()
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/transport/cmdstream.py", line 26, in do_final_close
    stream.close()
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/transport/cmdstream.py", line 222, in close
    self._close()
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/transport/adapterstream.py", line 273, in _close
    self.adapter.stop_sync()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 141, in stop_sync
    self.stop_scan()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 156, in stop_scan
    self._command_task.sync_command(['_stop_scan'])
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 741, in sync_command
    done_event.wait()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
(ota_dev) Matts-Macbook-Pro:coretools mrunchey$ 
```

Same issue happens in python2, but here ctrl-c doesn't actually exit the program (KeyboardInterrupt not being handled by threads properly, doing some investigation but will probably file a separate issue for how we handle termination calls given the bled112.py's threading implementation -- https://stackoverflow.com/questions/46161884/python-2-7-how-to-catch-keyboard-interrupt-in-program-with-more-than-25-threads for possible reference)

**Comment by mattrunchey** [comment]
Additionally, this appears to enable leaving the bled112 device in a bad state when connecting in the future (fixed by unplugging / replugging, or simply trying again, because the device is flushed)
```
(ota_dev) Matts-Macbook-Pro:coretools mrunchey$ iotile hw --port=bled112
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 51, in run
    res = getattr(self, cmd)(*args)
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 114, in _query_systemstate
    maxconn, = unpack("<B", response.payload)
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/utilities/packed.py", line 12, in unpack
    return struct.unpack(fmt, arg)
struct.error: unpack requires a buffer of 1 bytes
```

**Comment by mattrunchey** [comment]
Another note -- this seems to be happening "naturally". I don't even need to run a command for this error to happen, just have to wait 10-30 seconds for something to naturally propagate in the background.

**Comment by mattrunchey** [comment]
I rolled back my two latest changes to the bled112.py's quit behavior and the same thing is still happening (bug not caused by recent changes)

**Comment by mattrunchey** [comment]
I have now tested two USB-C to USB dongles, in all ports, with two different bled112 adapters. All ports have the same error after some time, though sometimes I didn't hit an error for several minutes or until I disconnected/reconnected in multiple iterations. Fairly sure it's not a hardware error.

I went and created a brand new environment using the upstream pip installation for coretools and bled112 plugin. Versions were 
```
iotile-core              3.22.12
iotile-transport-bled112 1.7.3  
```

Locally, I had installed 
```
iotile-core              3.22.12 /Users/mrunchey/gitrepos/coretools/iotilecore               
iotile-transport-bled112 1.8.0   /Users/mrunchey/gitrepos/coretools/transport_plugins/bled112
```

I rolled back my coretools commit to the last place 1.7.3 was checked in, and now the error is no longer happening, so the likely culprit is somewhere between the 1.7.3 change and 1.8.0 upgrade. The error is happening on line 530 of bled112.py added in the most recent update, https://github.com/iotile/coretools/blob/e47c5a770cba2660e735c997df745aff9287edc8/transport_plugins/bled112/iotile_transport_bled112/bled112.py#L530 

I need to dig in a bit to the behavior introduced here, but it appears there is a bug with the scan behavior here @ekkizogloy

**Comment by mattrunchey** [comment]
From what I can surmise, the packet can get malformed somewhere, or sent malformed from a badly programmed POD, and we should be more robust in our error handling here rather than always assuming a packet has the expected data fields. Would be nice to track down which device this was coming from but I can no longer reproduce the error (for the last ~30 minutes, nothing is going wrong)...

**Comment by mattrunchey** [comment]
Talked with @timburke a bit, oversight was that this parses *all* devices that send out bluetooth information and not all of them will be guaranteed to send the number of bytes we're expecting here. Will fix by adding some conditional handling and early-exit / packet drop for ones that don't meet our expected patterns.

**Comment by mattrunchey** [comment]
#521  submitted
