### ISSUE TITLE
iotile-updateinfo errors without -v flag on Python3

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#548]
Same command works on python2
```
(ota_dev) Matts-Macbook-Pro:coretools mrunchey$ iotile-updateinfo single-temp-base.trub 
Traceback (most recent call last):
  File "/Users/mrunchey/ota_dev/bin/iotile-updateinfo", line 11, in <module>
    load_entry_point('iotile-core', 'console_scripts', 'iotile-updateinfo')()
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/scripts/iotile_updateinfo_script.py", line 57, in main
    if verbosity >= len(loglevels):
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by timburke** [comment]
It looks like the `argparse` behavior changed from python 2 to 3 with respect to the the `count` action that defaults to 0 on python 2 and `None` on python 3:

https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/scripts/iotile_updateinfo_script.py#L48
