### ISSUE TITLE
iotile pull seems broken

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#601]
Called
```
iotile pull arch/prod_nfc300 *
```

```
Traceback (most recent call last):
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\iotile\core\scripts\iotile_script.py", line 208, in main
    finished = shell.invoke(line)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\typedargs\shell.py", line 494, in invoke
    val, line, finished = self.invoke_one(line)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\typedargs\shell.py", line 457, in invoke_one
    val = func(*posargs, **kwargs)
  File "<decorator-gen-63>", line 2, in pull
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\typedargs\utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\iotile\build\dev\pull_release.py", line 20, in pull
    chain.pull_release(name, ver, force=force)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\iotile\build\dev\resolverchain.py", line 102, in pull_release
    result = self.update_dependency(None, depdict, destdir)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\iotile\build\dev\resolverchain.py", line 149, in update_dependency
    result = resolver.resolve(depinfo, destdir)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\archbuild\resolvers\index_resolver.py", line 75, in resolve
    releases = hub.get_releases(owner, repo, filter_name=short_name)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\archbuild\hub.py", line 131, in get_releases
    releases = self._get_pageinated_list(url, headers)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\archbuild\hub.py", line 73, in _get_pageinated_list
    resp = requests.get(url, headers=headers)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\users\chris\iotile\env\prod_workspace\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '<https://api.github.com/repositories/80237961/releases?page=3'
```

My packages
```
(prod_workspace) PS C:\Users\chris\arch> pip list | grep iotile
arch-dms                             0.0.4       c:\users\chris\iotile\archtools\archdms
iotile-build                         2.6.15
iotile-cloud                         0.8.13
iotile-core                          3.23.1
iotile-ext-cloud                     0.6.0
iotile-gateway                       1.5.3
iotile-pcb                           0.6.5
iotile-sensorgraph                   0.7.2
iotile-ship                          0.1.4
iotile-support-con-nrf52832-2        2.15.4
iotile-support-firm-accelerometer-2  2.3.1
iotile-support-firm-arduino-bridge-0 0.2.0
iotile-support-firm-env-1            1.1.1
iotile-support-firm-gpio-3           3.0.0
iotile-support-lib-controller-3      3.7.9
iotile-test                          0.9.6
iotile-transport-bled112             1.7.3
iotile-transport-jlink               0.3.1
```

**Comment by timburke** [comment]
Looks like we have a bug in the pagination support for github releases in archbuild.  It doesn't pull out the url correctly.

**Comment by timburke** [comment]
`hub.py` _extract_next_page() needs a `strip()` on the url before removing the `<` and `>` characters because there is additional whitespace on pages after the second page.
