### ISSUE TITLE
Tracker App no longer works with old POD1M v1 firmware.

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#607]
Most commands do not work any more. 
Specifically `clear_trip`, `overview`, `trip_info`

```
(LogisticsTracker) overview
Traceback (most recent call last):
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/scripts/iotile_script.py", line 246, in main
    finished = shell.invoke_string(linebuf)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/shell.py", line 523, in invoke_string
    return self.invoke(args)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/shell.py", line 494, in invoke
    val, line, finished = self.invoke_one(line)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/shell.py", line 457, in invoke_one
    val = func(*posargs, **kwargs)
  File "<decorator-gen-107>", line 2, in overview
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "/Users/leekkizogloy/arch/src/fw/production_devices/product_applications/pod1m_shipping_tracker/python/tracker_app.py", line 261, in overview
    trip_info = self.trip_info()
  File "<decorator-gen-101>", line 2, in trip_info
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "/Users/leekkizogloy/arch/src/fw/production_devices/product_applications/pod1m_shipping_tracker/python/tracker_app.py", line 146, in trip_info
    uptime = test_iface.get_uptime()
  File "/Users/leekkizogloy/arch/src/fw/lib_controller/python/controllertest.py", line 103, in get_uptime
    uptime, = self.rpc(0x10, 0x0f, result_format="L")
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/proxy/plugin.py", line 16, in rpc
    return self._proxy.rpc(feature, cmd, *args, **kw)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/proxy/proxy.py", line 67, in rpc
    return unpack_rpc_payload("%s" % kw["result_format"], res['buffer'])
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/virtual/common_types.py", line 103, in unpack_rpc_payload
    return struct.unpack(code, payload)
error: unpack requires a string argument of length 4
```

**Comment by timburke** [comment]
Issue is due to the use of rtc related rpcs in the tracker_app that were not supported on POD-1m v1.  We need to inspect the app tag version and act appropriately
