### ISSUE TITLE
Subtle issue with scanning... it is possible that there is a race condition.

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#652]
Traceback (most recent call last):
  File "scan_waterfall.py", line 80, in <module>
    sw.collect_data()
  File "scan_waterfall.py", line 74, in collect_data
    scan_results = hw.scan()
  File "<decorator-gen-28>", line 2, in scan
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/typedargs/utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/hwmanager.py", line 891, in scan
    devices = self.stream.scan(wait=wait)
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/transport/cmdstream.py", line 115, in scan
    return sorted(self._scan(wait=wait), key=lambda x: x['uuid'])
  File "/Users/leekkizogloy/arch/env/py27/lib/python2.7/site-packages/iotile/core/hw/transport/adapterstream.py", line 110, in _scan
    for name, value in viewitems(self._scanned_devices):
RuntimeError: dictionary changed size during iteration

**Comment by mattrunchey** [comment]
I think this is inherent to the way we multithread. A quick fix would be to change that line to be `self._scanned_devices.copy()`.

**Comment by timburke** [comment]
Yeah that does look like a bug.  I may be able to fix it on Sunday but a workaround for it would be to just try/catch the RuntimeError and ignore and try again.  It should happen somewhat infrequently I would guess but maybe not.

**Comment by mattrunchey** [comment]
Actually, this part of the code only actually uses the values of the dictionary, so we can solve this in a 2/3 compatible way by converting the values to a list:

```
from future.utils import listitems
for value in listitems(self._scanned_devices):
  //logic
```

**Comment by timburke** [comment]
There's a quick fix for this.  While it's not safe to iterate over the potentially changing `_scanned_devices` dict since it could change, we can just iterate over a copy:

https://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3

```python
for key, value in viewitems(self._scanned_devices.copy()):
    # Have your fun.
```

I believe that it's important to use `.copy()` and not just `listitems()` since only `.copy()` is guaranteed to be atomic.  If `listitems` is specified somewhere to be atomic too then that's great but for example just doing `list(self._scanned_devices.items())` is not atomic on python 3:
https://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3

**Comment by mattrunchey** [comment]
I think `.copy` creates a shallow result, though - so if we delete the original dict, we lose the reference. Might need to do `deepcopy`.

**Comment by mattrunchey** [comment]
`listitems` from `future.utils` seems to directly create a new list out of the dictionary items, which should then be safe to iterate over even if you change the original dict:

```    
def listitems(d):
        return list(d.items())
```

From https://python-future.org/_modules/future/utils.html

**Comment by timburke** [comment]
> I think `.copy` creates a shallow result, though - so if we delete the original dict key, we lose the reference. Might need to do `deepcopy`.

I think a shallow copy should be enough here.  Deleting the original dict key will not invalidate our shallow copy, the only thing that would be problematic is if we modified the underlying dict key's value (by mutating one of its properties, not just assigning a new one to the same dict key).  That would cause the value of our shallow copy to update as well, which would be different from `deepcopy`.  I'm not sure if deepcopy is thread safe in the same was as `.copy()` though so that it cannot raise an exception if the dict happens to be modified during the deepcopy operation.

**Comment by timburke** [comment]
> `listitems` from `future.utils` seems to directly create a new list out of the dictionary items, which should then be safe to iterate over even if you change the original dict:
> 
> ```
> def listitems(d):
>         return list(d.items())
> ```
> From https://python-future.org/_modules/future/utils.html

The issue is not safety per se iterating over the result of `listitems()` but whether an exception can be raised by the `listitems()` if we get unlucky and `_scanned_devices` changes while `list()` is iterating over `d.items()`, which appears to be possible.  See:
https://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3

**Comment by mattrunchey** [comment]
Ok, right, I missed / forgot that the original intent isn't to protect the key/value pairs but to avoid invalidating the loop.

**Comment by mattrunchey** [comment]
As a side note, as well, the google python style guide suggests we shouldn't be relying on the atomicity of builtins anyways:
```
Do not rely on the atomicity of built-in types.
```
https://google.github.io/styleguide/pyguide.html#Threading

**Comment by vvynohradov** [comment]
@mattrunchey @timburke , we can create a Lock for _scanned_devices variable, and aquire it when _scanned_devices is used

**Comment by mattrunchey** [comment]
@vvynohradov I don't know that we want to involve a lock here, because we aren't concerned that the dictionary is changing because of its value, rather, we are simply trying to avoid an exception should the dictionary change size. If we cared about the integrity of the dictionary contents, a lock might be better. I think that it might just be a question of 'which is the more efficient path of removing the exception in our case -- creating a shallow copy, or locking access to the dictionary'. This might depend on which versions of Python we support, and the access pattern we'd expect of the dictionary (is there a lot of lock contention? if not, is the core implementation of lock supporting of a fast-lookup or is the operation expensive every time?)

@timburke I actually can't find a reference that declares `dict.copy()` to be atomic as opposed to list(dict). I was looking around for some clear answer, but past doing my own bytecode analysis I couldn't find a PEP article or anything saying it (the blog link that pointed out the issue with list doesn't point to an example or code that shows it). I was looking at [PyDict_Copy] in (https://github.com/python/cpython/blob/master/Objects/dictobject.c#L2551) and [generic copy](https://github.com/python/cpython/blob/master/Lib/copy.py#L66) that is referenced in the python docs...  I think we're actually just avoiding the exception because copy() and list() both don't actually care if the dictionary size changes during iteration, since it's essentially doing a recursive call rather than an iteration (but I have not fully delved past the copy.py implementation to see if that is actually true). I wrote a couple of scripts to try and get list() and dict.copy() to break, as well:

```
import threading, time

d = {}


def add_to_dict(d):
    i = 0
    while(1):
        i += 1
        d[i] = 5
        time.sleep(0.0001)


def read_from_dict(d):
    while(1):
        for key, value in d.copy().items():
            pass
        #print(len(d.keys()))


def read_from_dict_unsafe(d):
    while(1):
        for key, value in d.items():
            pass
        #print("hi mom")

t1 = threading.Thread(target=add_to_dict, args=(d,))
t2 = threading.Thread(target=read_from_dict, args=(d,))
#t2 = threading.Thread(target=read_from_dict_unsafe, args=(d,))

t1.start()
t2.start()
```
I never got the `read_from_dict` to crash with both copy() and list.

As an interesting side note, when I had the print statement uncommented in the `read_from_dict_unsafe`, I never got the "dict size changed during iteration" error, so it seems like the print statement has an interesting impact on the GIL for that function that somehow lets us avoid the "dict size changed during iteration" error. Fun!

**Comment by mattrunchey** [comment]
Ok, I learned a bit more this weekend, and think that both dict.copy() and list(dict) are operations that can, in crazy edge cases, get interrupted, but it is terribly unlikely to happen for both, and it actually won't break our operation (since we just care that the copy doesn't raise an exception, not about the integrity of the contents):
```
>>> dis.dis(dictcopy)
  2           0 LOAD_FAST                0 (d)
              2 LOAD_METHOD              0 (copy)
              4 CALL_METHOD              0
              6 STORE_FAST               1 (dc)
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE
>>> dis.dis(dictlist)
  2           0 LOAD_GLOBAL              0 (list)
              2 LOAD_FAST                0 (d)
              4 CALL_FUNCTION            1
              6 STORE_FAST               1 (dl)
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE
```
In Python2, I believe that the GIL is invoked every 1000 bytecodes -- that is, another thread can usurp control after that many operations have been executed since it was last grabbed. In Python3, I read that it's actually 15ms. 

In the `dictcopy` method, we load the dictionary in one bytecode, and then copy it in a second bytecode. In the case where that happens to be on the exact 15ms or 1k bytecode boundary, another thread could interrupt and modify the dictionary before we hit the copy method. We will always create a copy of the dictionary (but it may have been changed since we loaded it)

Similar story for `dictlist`. We load the function `list`, then we load the dict object `d`, we invoke the function call with one argument (`d` in this case), which does the actual work of creating the list (in a single bytecode), and then we store the result in `dl`. Again, here we can get unlucky and the object we loaded in the first bytecode can get changed before we actually call the CALL_FUNCTION bytecode, but since the actual work done by list, in CALL_FUNCTION, happens without interruption, we're always going to successfully copy the dictionary (just maybe not the same one we started with).

At least, that's roughly what I think the `dis` is saying here.
