### ISSUE TITLE
Warn instead of crash for entrypoints import

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#655]
When I installed an older version of a package, it registered an entry point to load on invocation of the module. However, that entry point had been removed in a future version, but there was still an `egg.info` link and we attempted to load it. We should instead log a warning and skip/continue.

Example:
```
pi@raspberrypi:~ $ iotile -vvvvv hw --port=virtual:tile_based@./tasks.json 
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/scripts/iotile_script.py", line 208, in main
    finished = shell.invoke(line)
  File "/home/pi/.local/lib/python2.7/site-packages/typedargs/shell.py", line 494, in invoke
    val, line, finished = self.invoke_one(line)
  File "/home/pi/.local/lib/python2.7/site-packages/typedargs/shell.py", line 457, in invoke_one
    val = func(*posargs, **kwargs)
  File "</home/pi/.local/lib/python2.7/site-packages/decorator.pyc:decorator-gen-18>", line 2, in __init__
  File "/home/pi/.local/lib/python2.7/site-packages/typedargs/utils.py", line 34, in _check_and_execute
    retval = func(*convargs, **convkw)
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/hw/hwmanager.py", line 85, in __init__
    self.stream = self._create_stream(adapter)
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/hw/hwmanager.py", line 834, in _create_stream
    return AdapterCMDStream(adapter_factory(port), port, conn_string, record=self._record)
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/hw/transport/virtualadapter.py", line 137, in __init__
    loaded_dev = self._load_device(name, config)
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/hw/transport/virtualadapter.py", line 206, in _load_device
    product_name="virtual_device"):
  File "/home/pi/.local/lib/python2.7/site-packages/iotile/core/dev/registry.py", line 167, in load_extensions
    ext = entry.load()
  File "/home/pi/.local/lib/python2.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named config_device
```

Here, `config_device` was registered in my `setup.py`, but when i updated the package without `config_device` in the new version, it didn't uninstall all of the old links (this is also possibly a problem with my sloppiness around virtual environments and local vs package install).

**Comment by DimaWittmann** [comment]
It should be fixed by PR(#682), related to ticket (#626 )
