### ISSUE TITLE
ctrl+C breaks in `iotile-gateway` (and possibly others) if you accidentally double book the bled112 dongle

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#657]
I was running `iotile-gateway` configured with bled112 as an adapter from one terminal.

In another terminal, I attempted to invoke `virtual_device bled112 virtual_device.py` . Since it, by default, tries to use the first bled112 dongle on the system (I have two and can avoid this by specifying the usbdev). A HardwareError ultimately gets raised, but the unexpected part is this seems to render exiting cleanly impossible (I had to ctrl+x and then kill -9 the pid). It would be nice if we could not have the ctrl+c handler break.

```
Traceback (most recent call last):
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/async_packet.py", line 75, in ReaderThread
    chunk = bytearray(filelike.read(remaining_length - len(remaining)))
  File "/Users/mrunchey/ap_dev/lib/python3.6/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
^CC-2019-01-30 11:25:33,702-main      :23   In quit signal handler.
C-2019-01-30 11:25:33,702-main      :26   Calling stop on gateway loop
C-2019-01-30 11:25:33,703-gateway   :165  Stopping gateway
I-2019-01-30 11:25:33,703-gateway   :166  Stopping gateway agents
C-2019-01-30 11:25:33,703-gateway   :174  Stopping device adapters
E-2019-01-30 11:25:33,704-bled112_cmd:156  Error stopping scan for devices, error=2
E-2019-01-30 11:25:33,704-gateway   :179  Error stopping device adapters
Traceback (most recent call last):
  File "/Users/mrunchey/ap_dev/lib/python3.6/site-packages/iotilegateway/gateway.py", line 177, in _stop_loop
    self.device_manager.stop()
  File "/Users/mrunchey/ap_dev/lib/python3.6/site-packages/iotilegateway/device.py", line 71, in stop
    adapter.stop_sync()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 140, in stop_sync
    self.stop_scan()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 156, in stop_scan
    self._command_task.sync_command(['_stop_scan'])
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 745, in sync_command
    raise HardwareError("Error executing synchronous command", command=cmd, return_value=retval)
iotile.core.exceptions.HardwareError: HardwareError: Error executing synchronous command
Additional Information:
command: ['_stop_scan']
return_value: {'reason': 'Could not stop scan for ble devices'}
C-2019-01-30 11:25:33,711-gateway   :194  Stopping event loop and shutting down
C-2019-01-30 11:25:33,712-gateway   :141  Done stopping loop
^[[A^CC-2019-01-30 11:25:38,275-main      :23   In quit signal handler.
C-2019-01-30 11:25:38,275-main      :26   Calling stop on gateway loop
^CC-2019-01-30 11:25:39,284-main      :23   In quit signal handler.
C-2019-01-30 11:25:39,284-main      :26   Calling stop on gateway loop
^CC-2019-01-30 11:25:40,311-main      :23   In quit signal handler.
C-2019-01-30 11:25:40,311-main      :26   Calling stop on gateway loop
^X^Z
[1]+  Stopped                 iotile-gateway --config=simple_gateway.conf
```

**Comment by timburke** [comment]
This has been an issue for awhile but one thing we should do is open the ports exclusively when running on linux, mac:
https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.__init__

That will raise an exception when you accidentally connect to the same dongle and not corrupt the other user's data stream.  This does not work on windows so we would need to check the os before setting the flag (unless it is a safe no-op on windows rather than raising a not-supported error, I'm not sure)

**Comment by vvynohradov** [comment]
Hello @timburke,
I checked source code of pyserial module, when it is used on Windows, it ignores **exclusive** flag it. I will make additional check today and then create a pull request

**Comment by mattrunchey** [comment]
While exclusively loading the ports is a good thing to do, it doesn't fix the core issue we have here.

Digging in to the `iotile-gateway` loop, without exclusive locks (the fixes in that PR), We can see the signal handling by the ctrl+c command in the gateway code starts at main.py. It *appears* that we properly get to loop.stop() and should close things out, but it's clear that we're missing one of the background threads:
```
C-2019-02-13 14:26:46,207-main      :26   Calling stop on gateway loop
C-2019-02-13 14:26:46,208-gateway   :168  Stopping gateway
I-2019-02-13 14:26:46,208-gateway   :169  Stopping gateway agents
C-2019-02-13 14:26:46,208-gateway   :177  Stopping device adapters
E-2019-02-13 14:26:49,211-gateway   :182  Error stopping device adapters
Traceback (most recent call last):
  File "/Users/mrunchey/gitrepos/coretools/iotilegateway/iotilegateway/gateway.py", line 180, in _stop_loop
    self.device_manager.stop()
  File "/Users/mrunchey/gitrepos/coretools/iotilegateway/iotilegateway/device.py", line 71, in stop
    adapter.stop_sync()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 142, in stop_sync
    self.stop_scan()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 158, in stop_scan
    self._command_task.sync_command(['_stop_scan'])
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112_cmd.py", line 745, in sync_command
    raise HardwareError("Error executing synchronous command", command=cmd, return_value=retval)
iotile.core.exceptions.HardwareError: HardwareError: Error executing synchronous command
Additional Information:
command: ['_stop_scan']
C-2019-02-13 14:26:49,220-gateway   :197  Stopping event loop and shutting down
C-2019-02-13 14:26:49,221-gateway   :143  Done stopping loop
```

What we have happening is an unhandled exception in the device IOLoop, so it never gets to the part where the IOLoop should stop, because it never successfully/cleanly closes:
```        
except InternalTimeoutError:
            return False, {'reason': "Timeout waiting for response"}
```

Ultimately what's keeping the loop alive with stuff forever is the fact that `self.scanning` doesn't get set to false when `stop_scan` fails to execute its sync_command:
```
    def stop_scan(self):
        """Stop the scanning task"""
        self._command_task.sync_command(['_stop_scan'])
        self.scanning = False
```

I modified the stop_scan to always set scanning = False and that enables the `gateway.py` loop to close cleanly. 

I don't see a clear way to denote the circumstance we want to invoke to close down here, as forcing the setting here could cause the BLED112 instance to leave in a weird state (such as not actually cleanly closing the serial port, though I haven't seen it come up as an issue yet).

@timburke  -- do you see a better way to improve the shutdown logic in weird states for the gateway, or is this something we may have to live with and try to fix the root cause if it comes up in another circumstance (i.e. by opening the serial exclusively, we remove the only encountered pattern to get us to this state)?

**Comment by timburke** [comment]
@vvynohradov @mattrunchey The underlying issue is that our `stop_sync` logic in the bled112 transport plugin does not guarantee that it stops the background thread if there is a problem stopping scanning (or disconnecting from connected devices).

### Context

Since the BLED112 dongle runs its own BLE stack, whatever state it is in will naturally persist when our application closes down and the OS will not clean up after ourselves. So, for example, if we are connected to a ble device, the dongle will remain connected forever if we close our application without telling it to explicitly disconnect.  The same goes for scanning.  The dongle will go on scanning forever if we allow the application to quit without stopping it.

So that's the goal of `stop_sync` is to make sure we put the dongle back into a state where it is not scanning or connected to any devices.  Note that we also do this check when we start up the process in case there was an unclean shutdown so that we can always recover the dongle into a known state. 

Note that this `stop_sync` behavior is opportunistic in the sense that it is not 100% fool-proof.  For example, if our process is hard-killed `kill -9` or Ctrl-Break on Windows, we have no opportunity to clean up and the dongle will remain connected, scanning etc.  That's unavoidable and generally fine since we recover on process restart anyway.  The issue is that the python interpreter has a `join()` call on all background threads not marked as daemon at interpreter shutdown so unless we cleanly stop the BLED112CommandProcessor thread, we hang the process.  

Normally, the `_stop_scan()` and `_disconnect` calls cannot fail, unless we have lost synchronization with the dongle by, e.g. another process also writing to its serial port so `stop_sync()` does not thrown any exceptions and we eventually get to the lines that cleanly stop the background threads:
https://github.com/iotile/coretools/blob/master/transport_plugins/bled112/iotile_transport_bled112/bled112.py#L179

However, if `_stop_scan()` or `_disconnect` throws then we never get there an guarantee a hang on exit until you hard-kill the process.  

We should wrap these calls in a try/finally to make sure that we always stop the background thread no matter what happens so we don't hang on exit even if we are somehow unable to communicate with the dongle.

**Comment by timburke** [comment]
@mattrunchey 
To your comment about the root cause of why we hang, it's basically this.  Our ctrl-C handler does correctly get invoked and correctly call our stop_loop routine, it's just that we need to guarantee that we always stop all background threads in that handler no-matter what or the python interpreter hangs on shutdown.  That's the underlying issue here.

Note that you have this same problem when using `HardwareManager(port="bled112")` from a script.  It needs to make sure to stop the background thread managing the dongle on quit so it registers an `atexit` handler.  However if an exception is raised all the way to the main() level of the script, then python does not run atexit handlers and the background thread does not get closed leading to the script hanging in a `thread.join()` at exit and needing to be hard-killed.  That's why the only safe way to use `HardwareManager` in a script is in a `with HardwareManager` clause so that we always stop the dongle thread no matter what.

**Comment by timburke** [comment]
Note that this will get better when we move to python 3 only and can use asyncio and coroutines to manage the dongle since that will not have these background threads hanging the interpreter at shutdown.
