### ISSUE TITLE
`struct.pack` rounding error in `pack_rpc_payload`

### ISSUE THREAD

**Issue by Djou-ECP** [iotile/coretools#739]
## Float packing error

In `pack_rpc_payload` (`iotile/core/hw/virtual/common_types.py`) .
When packing floats, the `pack` function of the `struct` package may introduce an error on the packed value that causes the validation to fail. The validation should take this behavior into account. The issue affects both `rpc` and `rpc_v2`.
Here is an example with `pack_rpc_payload` : 

```
>>> from iotile.core.hw.virtual import pack_rpc_payload
>>> arg_format = "f"
>>> args = [2.6]
>>> pack_rpc_payload(arg_format, args)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julienraspaud/espaceProject/candidate_coding_challenges/radiation/.venv/lib/python3.7/site-packages/iotile/core/hw/virtual/common_types.py", line 100, in pack_rpc_payload
    code=code, args=args)
iotile.core.hw.virtual.common_types.RPCInvalidArgumentsError: RPCInvalidArgumentsError: Passed values would be truncated, please validate the size of your string
Additional Information:
code: <f
args: [2.6]
```

Here is an example of `struct.pack`'s behavior : 

```
>>> import struct
>>> code = "<f"
>>> args = [2.6]
>>> packed_result = struct.pack(code, *args)
>>> unpacked_validation = struct.unpack(code, packed_result)
>>> print(unpacked_validation)
(2.5999999046325684,)
```

### Information

Python version : 3.7.2

Versions of iotile dependencies installed: 
```
iotile-core==4.1.0
iotile-test==1.0.2
iotile-transport-bled112==2.0.2
```  

System :
```
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G1815
```

**Comment by mattrunchey** [comment]
This is because Python uses double precision floats, taking 8 bytes, so you need to pack with 'd' to retain full precision.

```
>>> import struct
>>> code = "<f"
>>> code2 = "<d"
>>> args = [2.6]
>>> packed_result = struct.pack(code, *args)
>>> packed_result2 = struct.pack(code2, *args)
>>> unpacked_validation = struct.unpack(code, packed_result)
>>> unpacked_validation2 = struct.unpack(code2, packed_result2)
>>> unpacked_validation
(2.5999999046325684,)
>>> unpacked_validation2
(2.6,)
>>> 
```

**Comment by mattrunchey** [comment]
However, this is indeed not the intent of the packing validation check. For now you can workaround it by packing before sending to the RPC or using `d` as the pack code, we will work on a proper fix or warning system for this.
