### ISSUE TITLE
Commits after iotilecore-4.1.1 seems to break the jlink interface.

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#792]
I’m having some issues with the current iotile-core head version.

```
(py3) ✔ ~/arch/src/sw/coretools/iotilecore [master|✔] 
21:19 $ iotile -vvvvv hw --port=jlink
19-04-11 21:20:06.196 DEB iotile.core.utilities.async_tools.event_loop Starting event loop
19-04-11 21:20:06.196 DEB asyncio Using selector: KqueueSelector
19-04-11 21:20:06.196 DEB iotile.core.utilities.async_tools.event_loop Starting loop in background thread
19-04-11 21:20:06.196 DEB iotile.core.utilities.async_tools.event_loop Added primary task LegacyAdapter (JLinkAdapter)
19-04-11 21:20:06.197 DEB iotile.core.utilities.async_tools.event_loop Added subtask periodic task for JLinkAdapter to parent LegacyAdapter (JLinkAdapter)
19-04-11 21:20:06.221 DEB iotile.core.dev.registry Creating dynamic support wheel package: iotile_support_firm_gpiopipe_1
19-04-11 21:20:06.222 DEB iotile.core.dev.registry Importing module as subpackage: iotile_support_firm_gpiopipe_1.gpiopipe_proxy
19-04-11 21:20:06.324 WAR iotile.core.dev.registry Unable to load mqtt from Distribution('arch_gateway', '2.2.0')
Traceback (most recent call last):
  File "/Users/lukee/arch/src/sw/coretools/iotilecore/iotile/core/dev/registry.py", line 167, in load_extensions
    ext = entry.load()
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/Users/lukee/arch/env/py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/arch_gateway/tasks/mqtt_forwarder/__init__.py", line 3, in <module>
    from .forwarder import MQTTForwarderTask
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/arch_gateway/tasks/mqtt_forwarder/forwarder.py", line 18, in <module>
    from ..task import DaemonTask
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/arch_gateway/tasks/task.py", line 13, in <module>
    from iotilegateway.supervisor import ServiceStatusClient
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotilegateway/supervisor/__init__.py", line 1, in <module>
    from .status_client import ServiceStatusClient, AsyncServiceStatusClient
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotilegateway/supervisor/status_client.py", line 10, in <module>
    from iotile.core.utilities.validating_wsclient import ValidatingWSClient, AsyncValidatingWSClient
ModuleNotFoundError: No module named 'iotile.core.utilities.validating_wsclient'
(HardwareManager)
``` 
iotile-core version 4.1.1 that is currently on pypi does not have this error.
This is the output from currently released 4.1.1
```
(py3) ✔ ~/arch/src/sw/coretools/iotilecore [master|✔] 
21:22 $ iotile -vvvvv hw --port=jlink
19-04-11 21:22:12.572 DEB iotile.core.dev.registry Creating dynamic support wheel package: iotile_support_firm_gpiopipe_1
19-04-11 21:22:12.573 DEB iotile.core.dev.registry Importing module as subpackage: iotile_support_firm_gpiopipe_1.gpiopipe_proxy
(HardwareManager)
``` 

I was able to rebase my changes onto iotilecore-4.1.1 tag and the `read_ram` debug function seems to be working.

```
(py3) ✔ ~/arch/src/sw/coretools [feat-debug-read-ram-rebase L|✚ 1…1] 
21:54 $ iotile hw --port=jlink:mux=ftdi connect_direct device="nrf52;channel=0" debug
(DebugManager) read_ram 0x100000a4 8
8d21e6f4e3b7eede
(DebugManager) read_ram 0x100000a4 4
8d21e6f4
(DebugManager) read_ram 0x100000a8 4
e3b7eede
(DebugManager) read_ram 0x10001080 4
ffffffff
(DebugManager) quit
(py3) ✔ ~/arch/src/sw/coretools [feat-debug-read-ram-rebase L|✚ 1…1] 
21:59 $ iotile hw --port=bled112 scan
{
    "advertising_version": 2,
    "battery": 3.28125,
    "broadcast_toggle": 0,
    "connection_string": "F7:E3:F4:E6:21:8D",
    "expiration_time": "2019-04-11 22:00:16.319135",
    "low_voltage": false,
    "pending_data": false,
    "reboot_counter": 0,
    "sequence": 31,
    "signal_strength": -48,
    "slug": "d--0000-0000-0000-000a",
    "timestamp": 280,
    "user_connected": false,
    "uuid": 10
}
```

Above is an example of `read_ram()` working. The MAC address can be read.

**Comment by mattrunchey** [comment]
Ah, so, in a recent PR we moved master to a pre-release of the asyncio upgrade and froze 4.x fixes in the `v4.x` branch. Try using that branch for install/commits for now.

**Comment by mattrunchey** [comment]
Essentially, we've temporarily probably broken `master` for a lot of things, so until we stabilize you'll need to temporarily use `v4.x` while we fix up stuff like this.

**Comment by mattrunchey** [comment]
In particular, though, your error is likely coming from not also having the `iotilegateway` package also installed from master

**Comment by timburke** [comment]
The warning above is unrelated to `jlink`.  It seems that you had `iotile-core` installed from HEAD and `iotile-gateway` installed from pypi, which causes the issue because the released `iotile-gateway` is not compatible with the current changes in head (though the version of `iotile-gateway` that is currently in master *is compatible*).  

You can fix this by uninstalling `iotile-gateway` and reinstalling the version from `master`.

**Comment by timburke** [comment]
@ekkizogloy Note that you would have gotten the same warning whether you used `jlink` or any other transport plugin.

**Comment by timburke** [comment]
No activity and appears to not be a bug so closing
