### ISSUE TITLE
Spurious bled112 device adapter error on asyncio

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#808]
Using virtual_device to serve bled112 access, I connected from a remote host. After "quitting", it seems to identify that the connection dropped, but when reconnecting there is an error message suggesting that the adapter didn't fully disconnect. The connection does get made successfully, though, and the conn_id increments properly:

```
19-04-30 21:14:41.632 DEB iotile_transport_bled112.server_bled112 Received disconnect event
19-04-30 21:14:41.633 DEB iotile_transport_bled112.server_bled112 Reenabling advertisements after disconnection
19-04-30 21:14:53.734 DEB iotile_transport_bled112.server_bled112 Received connect event
19-04-30 21:14:53.735 ERR asyncio Task exception was never retrieved
future: <Task finished coro=<BLED112Server.on_connect() done, defined at /home/pi/coretools/transport_plugins/bled112/iotile_transport_bled112/server_bled112.py:241> exception=DeviceAdapterError()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/coretools/transport_plugins/bled112/iotile_transport_bled112/server_bled112.py", line 245, in on_connect
    await self.connect(self.CLIENT_ID, str(self.device.iotile_id))
  File "/home/pi/coretools/iotilecore/iotile/core/hw/transport/server/standard.py", line 262, in connect
    await self.adapter.connect(conn_id, conn_string)
  File "/home/pi/coretools/iotilecore/iotile/core/hw/transport/virtualadapter.py", line 235, in connect
    raise DeviceAdapterError(conn_id, 'connect', 'device already connected')
iotile.core.hw.exceptions.DeviceAdapterError: DeviceAdapterError: Operation connect on conn 3 failed because device already connected
Additional Information:
conn_id: 3
reason: device already connected
operation: connect
19-04-30 21:14:54.203 DEB iotile_transport_bled112.server_bled112 Opening rpc interface
```

**Comment by mattrunchey** [comment]
Similarly, this may be an issue with the `iotile` utility:

```
(HardwareManager) disconnect
DeviceAdapterError: Operation disconnect on conn 0 failed because Invalid connection_id
Additional Information:
conn_id: 0
reason: Invalid connection_id
operation: disconnect
(HardwareManager) connect 1
HardwareError: Cannot connect when we are already connected
```

(This happens if I close the remote, but not the local -- as if the connection ID gets culled but that signal isn't fully routed back to the utility)
