### ISSUE TITLE
iotile-sgcompile Python 3 incompatability

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#813]
```
13:42 $ iotile-sgcompile -f snippet app_2057.sgf
Traceback (most recent call last):
  File "/Users/lukee/arch/env/py3/bin/iotile-sgcompile", line 10, in <module>
    sys.exit(main())
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/sg/scripts/iotile_sgcompile.py", line 78, in main
    output = output_format.format(parser.sensor_graph)
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/sg/output_formats/snippet.py", line 66, in format_snippet
    conf_val = 'hex:' + hexlify(conf_val)
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by ekkizogloy** [comment]
Python 2 Output:
```
13:44 $ iotile-sgcompile -f snippet app_2057.sgf
disable
clear
reset
add_node "(input 1 always) => unbuffered 1024 using copy_latest_a"
add_node "(unbuffered 1024 always) => unbuffered 40 using copy_latest_a"
add_streamer 'unbuffered 40' 'controller' True individual broadcast
persist
back
config_database
clear_variables
set_variable 'controller' 8192 uint32_t 1
set_variable 'controller' 1 uint32_t 80
set_variable 'slot 1' 32768 binary hex:0201d00701000400
set_variable 'slot 1' 32769 binary hex:000006040001040400020500
set_variable 'slot 1' 32770 uint16_t 1
set_variable 'slot 1' 32771 uint8_t 1
set_variable 'slot 1' 32772 binary hex:ffffffff
set_variable 'slot 1' 32773 binary hex:ffffffff
back
reset
```

**Comment by ekkizogloy** [comment]
Here is a link to the SGF file. 

https://github.com/iotile/production_devices/blob/master/customer_prototypes/proto_pulse_counter/sensorgraphs/app_2057.sgf

**Comment by timburke** [comment]
@mattrunchey The fix should go the other way.  The hexlify should `.decode('utf-8') into a `str` since the output here is being written to a text file

**Comment by mattrunchey** [comment]
Ah, gotcha.

As a side note, interesting that py3.5 gives a different exception reason than py3.7:
```
(v.8) Matts-Macbook-Pro:coretools mrunchey$ iotile-sgcompile -f snippet app_2057.sgf 
Traceback (most recent call last):
  File "/Users/mrunchey/v.8/bin/iotile-sgcompile", line 11, in <module>
    load_entry_point('iotile-sensorgraph', 'console_scripts', 'iotile-sgcompile')()
  File "/Users/mrunchey/gitrepos/coretools/iotilesensorgraph/iotile/sg/scripts/iotile_sgcompile.py", line 78, in main
    output = output_format.format(parser.sensor_graph)
  File "/Users/mrunchey/gitrepos/coretools/iotilesensorgraph/iotile/sg/output_formats/snippet.py", line 66, in format_snippet
    conf_val = 'hex:' + hexlify(conf_val)
TypeError: Can't convert 'bytes' object to str implicitly
```
