### ISSUE TITLE
iotile-ext-cloud missing msgpack dependency

### ISSUE THREAD

**Issue by timothyfroehlich** [iotile/coretools#831]
In a docker container containing the following pip install line:

```RUN pip3 install \
    boto3 \
    iotile-ext-cloud \
    progressbar```

I ran a script with the following imports:
```import boto3
import tempfile
import subprocess
import time
import argparse

from iotile.cloud.utilities import device_slug_to_id
from pathlib import Path
from progressbar.progressbar import ProgressBar

```

And got the following:

```Traceback (most recent call last):
  File "/app/sdcard-flasher.py", line 7, in <module>
    from iotile.cloud.utilities import device_slug_to_id
  File "/usr/local/lib/python3.6/dist-packages/iotile/cloud/__init__.py", line 2, in <module>
    from .cloud import IOTileCloud
  File "/usr/local/lib/python3.6/dist-packages/iotile/cloud/cloud.py", line 15, in <module>
    from iotile.core.hw.reports import IndividualReadingReport, SignedListReport, FlexibleDictionaryReport
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/__init__.py", line 2, in <module>
    from .proxy import TileBusProxyObject
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/proxy/__init__.py", line 9, in <module>
    from .proxy import TileBusProxyObject
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/proxy/proxy.py", line 15, in <module>
    from ..virtual import pack_rpc_payload, unpack_rpc_payload
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/virtual/__init__.py", line 119, in <module>
    from .virtualdevice_base import BaseVirtualDevice, AbstractAsyncDeviceChannel
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/virtual/virtualdevice_base.py", line 9, in <module>
    from ..reports.individual_format import IndividualReadingReport
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/reports/__init__.py", line 6, in <module>
    from .flexible_dictionary import FlexibleDictionaryReport
  File "/usr/local/lib/python3.6/dist-packages/iotile/core/hw/reports/flexible_dictionary.py", line 4, in <module>
    import msgpack
ModuleNotFoundError: No module named 'msgpack'
```

Adding msgpack to my pip install fixed it.

**Comment by timburke** [comment]
Confirmed.  It looks like we missed the `msgpack` dependency from `iotile-core` as part of the upgrade:
https://github.com/iotile/coretools/blob/master/iotilecore/setup.py#L27

**Comment by timburke** [comment]
This breaks the internal firmware CI system that now fails to build all firmware images.  @mattrunchey can you fix the missing `iotile-core` dependency and release a quick patch version?
