### ISSUE TITLE
iotile-gateway seems to stop sending broadcasts after a while

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#837]
the new `iotile-gateway` seems to stop sending broadcast data to connected services after a short period of time after connecting. We are investigating and will update this ticket as we learn more.

**Comment by mattrunchey** [comment]
Progress update:

What actually appears to stop working is the `websockets` device adapter. Still narrowing down root cause, but it seems to be a data volume error that's causing the websocket server on the iotile-gateway to stop sending notifications, as well as stop listening for new connection requests (i.e. attempting to re-establish a connection to the `ws:` that the gateway establishes fails silently)

**Comment by mattrunchey** [comment]
@timburke let me know if this gives you any ideas.

On the client side, what happens is we eventually get forcibly disconnected from the websocket server:

```shell
[ERROR] 19-06-06 21:41:16.874 Error calling callback for event __internal_ws_disconnect_event, payload=None
                                                                               Traceback (most recent call last):
                                                                                 File "/usr/lib/python3.5/asyncio/tasks.py", line 242, in _step
                                                                                   result = coro.throw(exc)
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 674, in transfer_data
                                                                                   message = yield from self.read_message()
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 742, in read_message
                                                                                   frame = yield from self.read_data_frame(max_size=self.max_size)
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 815, in read_data_frame
                                                                                   frame = yield from self.read_frame(max_size)
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 884, in read_frame
                                                                                   extensions=self.extensions,
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/framing.py", line 99, in read
                                                                                   data = yield from reader(2)
                                                                                 File "/usr/lib/python3.5/asyncio/streams.py", line 668, in readexactly
                                                                                   yield from self._wait_for_data('readexactly')
                                                                                 File "/usr/lib/python3.5/asyncio/streams.py", line 458, in _wait_for_data
                                                                                   yield from self._waiter
                                                                                 File "/usr/lib/python3.5/asyncio/futures.py", line 381, in __iter__
                                                                                   yield self  # This tells Task to wait for completion.
                                                                                 File "/usr/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
                                                                                   future.result()
                                                                                 File "/usr/lib/python3.5/asyncio/futures.py", line 286, in result
                                                                                   raise CancelledError
                                                                               concurrent.futures._base.CancelledError
                                                                               
                                                                               The above exception was the direct cause of the following exception:
                                                                               
                                                                               Traceback (most recent call last):
                                                                                 File "/usr/lib/python3.5/site-packages/iotile_transport_websocket/generic/async_client.py", line 169, in _manage_connection
                                                                                   message = await self._con.recv()
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 434, in recv
                                                                                   yield from self.ensure_open()
                                                                                 File "/usr/lib/python3.5/site-packages/websockets/protocol.py", line 658, in ensure_open
                                                                                   ) from self.transfer_data_exc
                                                                               websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```


It led me to look at the websocket package itself, but when I turned on its logger to full debug, there was no exception to be seen -- it was just full of debug frames.

The logs on the server (the gateway itself) get `await socket.send()` errors at the same time that the client gets the above exception (the time doesn't line up on this one, but it looks like this):
```
19-06-06 21:49:38.612 WAR asyncio socket.send() raised exception.
```

This exception gets repeated continually (it never detects that the client is closed). When you reconnect the client, you finally end up invoking the connection clean up, but the new client never ends up connecting to the websocket server successfully -- the `iotile-gateway` must be fully rebooted, which indicates that something on the server side is getting stuck.

**Comment by timburke** [comment]
Nothing jumps out to me yet but there are a few issues on `websockets` that might be related:

https://github.com/aaugustin/websockets/issues/367
https://github.com/aaugustin/websockets/issues/618

Not sure though.  It could (unfortunately), be a race inside the `websockets` package

**Comment by mattrunchey** [comment]
I tried to pull out the full exception from that connection closed, and it says it's an `asyncio.Cancelled` error.  (I was hoping for something more like what was found in https://github.com/aaugustin/websockets/issues/587 ) but we (fortunately?) don't have a max_size error..

I added `ping_interval=None` in the async_client connection and that actually seems to have stabilized the connection (broadcasts have been going for... 5 minutes now), but there may be a memory leak in the iotile-gateway side. VSZ is on an extreme upward trend with no signs of stopping. I ended up killing the process and will look there. I'm guessing that the ping_interval was being exceeded due to the size of some object on the server side that caused the client to think it was disconnected, but am surprised that there wasn't a better error describing that.

**Comment by mattrunchey** [comment]
The broadcast_forwarder still ends up erroring out later, but this time with a different error code (`1011`), which I'm guessing is due to a queue getting full somewhere. Getting closer...

**Comment by mattrunchey** [comment]
I believe this is a load issue. After leaving it on for several minutes, the UTC timestamps that are reading out of the broadcast reader are 400 seconds behind. Restarting the gateway and reconnecting accelerates the timestamps to the current unix timestamp, and it slowly falls behind over time (and memory size increases).

**Comment by mattrunchey** [comment]
Further evidence from the documentation suggests that we were getting 1006 earlier indeed because our frame fell too far behind (our client never got to the pong before the timeout was reached):
```
   Once the connection is open, a `Ping frame`_ is sent every
    ``ping_interval`` seconds. This serves as a keepalive. It helps keeping
    the connection open, especially in the presence of proxies with short
    timeouts. Set ``ping_interval`` to ``None`` to disable this behavior.

    .. _Ping frame: https://tools.ietf.org/html/rfc6455#section-5.5.2
```

There is a max_queue default that suggests that the server might not be the bottleneck:
```
    The ``max_queue`` parameter sets the maximum length of the queue that holds
    incoming messages. The default value is 32. 0 disables the limit. Messages
    are added to an in-memory queue when they're received; then :meth:`recv()`
    pops from that queue. In order to prevent excessive memory consumption when
    messages are received faster than they can be processed, the queue must be
    bounded. If the queue fills up, the protocol stops processing incoming data
    until :meth:`recv()` is called. In this situation, various receive buffers
    (at least in ``asyncio`` and in the OS) will fill up, then the TCP receive
    window will shrink, slowing down transmission to avoid packet loss.
```


Fundamentally, this means that we need to either reduce the volume of broadcasts going through the gateway, consume packets more quickly, or increase the throughput of the server itself. I still haven't quite identified what in particular is slow. It may be worth noting that the `iotile-gateway` service is taking up a full 25% of a quad core processor, indicating that is the process which is slowing things down (the client process is lower, at around 15%).


Another thing I've noticed is that this directly impacts how long it takes new clients to connect, likely due to https://github.com/iotile/coretools/blob/a8306de93e72a81542fa339cea2b827bb79f2e10/transport_plugins/websocket/iotile_transport_websocket/device_server.py#L242 . The server will continue to try and send every packet to the client, as it never disconnects, and the queue needs to be worked through before the new connection request is serviced. I observed this by quickly disconnecting a client, before it got backed up, and starting a new one. The longer in to the running process I do this, the longer it takes the connection to be established (to the point where it can take several minutes to connect).

**Comment by timburke** [comment]
Understood.  Thanks for tracking down the root cause here @mattrunchey.  It sounds like we have a performance bottleneck somewhere in the broadcast processing code which, I guess, is not unexpected given that we haven't paid too much attention to optimizing that.  

One immediate thing we could do is deduplicate the broadcasts at the bled112 level and see how much that helps to try to identify if the performance issue is inside the bled112 or elsewhere in the code, see:
https://github.com/iotile/coretools/blob/master/transport_plugins/bled112/iotile_transport_bled112/config_variables.py#L9

Can you see if applying that config variable results in any meaningful decrease in cpu usage?

**Comment by mattrunchey** [comment]
I applied it but we're still stuck right up at max CPU for the core. This is the debug output for the reports that are gettinig serialized/sent to the ws server with that setting enabled (`iotile config set bled112:throttle-broadcast true`):
```
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.363 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3004, 'encoded_report': b'AwAQALwLAABO+AQAAAAAACgQAAAAAAAATvgEAOoBAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 714794)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.379 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2991, 'encoded_report': b'AwAQAK8LAACEHAUAAAAAACgQAAAAAAAAhBwFAAAAAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 715978)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.382 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3044, 'encoded_report': b'AwAQAOQLAAAkHQUAAAAAACgQAAAAAAAAJB0FANsAAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 717248)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.386 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3018, 'encoded_report': b'AwAQAMoLAABQ9gQAAAAAACgQAAAAAAAAUPYEAC8GAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 718466)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.398 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3027, 'encoded_report': b'AwAQANMLAADcGgQAAAAAACgQAAAAAAAA3BoEAI4IAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 723220)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.402 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3019, 'encoded_report': b'AwAQAMsLAACF9gQAAAAAACgQAAAAAAAAhfYEABkGAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 725226)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.407 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2982, 'encoded_report': b'AwAQAKYLAADyHAUAAAAAACgQAAAAAAAA8hwFACkHAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 726475)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.412 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3000, 'encoded_report': b'AwAQALgLAAAS+AQAAAAAACgQAAAAAAAAEvgEAMkCAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 728395)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.446 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3016, 'encoded_report': b'AwAQAMgLAAB49gQAAAAAACgQAAAAAAAAePYEADkGAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 729736)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.451 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2991, 'encoded_report': b'AwAQAK8LAACEHAUAAAAAACgQAAAAAAAAhBwFAAAAAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 732208)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.456 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2996, 'encoded_report': b'AwAQALQLAADUHAUAAAAAACgQAAAAAAAA1BwFAIkDAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 733454)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.461 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3061, 'encoded_report': b'AwAQAPULAABerQMAAAAAACgQAAAAAAAAXq0DAPgTAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 734711)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.510 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3031, 'encoded_report': b'AwAQANcLAACCGgQAAAAAACgQAAAAAAAAghoEAFQJAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 736783)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.516 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3027, 'encoded_report': b'AwAQANMLAADcGgQAAAAAACgQAAAAAAAA3BoEAI4IAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 737984)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.520 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3019, 'encoded_report': b'AwAQAMsLAACF9gQAAAAAACgQAAAAAAAAhfYEABkGAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 739201)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.524 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2994, 'encoded_report': b'AwAQALILAACYHAUAAAAAACgQAAAAAAAAmBwFAAEHAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 740959)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.529 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3319, 'encoded_report': b'AwAQAPcMAABSdQEAAAAAACgQAAAAAAAAUnUBAPABAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 742672)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.534 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3020, 'encoded_report': b'AwAQAMwLAABI9gQAAAAAACgQAAAAAAAASPYEAJwGAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 744062)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.543 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2993, 'encoded_report': b'AwAQALELAAD8HAUAAAAAACgQAAAAAAAA/BwFAD4HAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 745696)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.547 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3318, 'encoded_report': b'AwAQAPYMAABIdQEAAAAAACgQAAAAAAAASHUBAFUAAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 746877)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.586 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2986, 'encoded_report': b'AwAQAKoLAACOHAUAAAAAACgQAAAAAAAAjhwFAOsCAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 748436)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.590 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2801, 'encoded_report': b'AwAQAPEKAABgcjcAAAAAACgQAAAAAAAAYHI3AGCbAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 749697)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.746 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3000, 'encoded_report': b'AwAQALgLAAAS+AQAAAAAACgQAAAAAAAAEvgEAMkCAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 853543)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.780 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 2796, 'encoded_report': b'AwAQAOwKAAAcsVUAAAAAACgQAAAAAAAAHLFVANLUAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 855894)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.784 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3028, 'encoded_report': b'AwAQANQLAADcGgQAAAAAACgQAAAAAAAA3BoEAMkIAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 858320)}}

```

**Comment by timburke** [comment]
@mattrunchey The throttling must be broken then so it makes sense that it doesn't do anything to help.  See the two lines:

```
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.412 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3000, 'encoded_report': b'AwAQALgLAAAS+AQAAAAAACgQAAAAAAAAEvgEAMkCAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 728395)}}
Jun 07 16:10:06 d--1182 iotile-gateway[10401]: 19-06-07 16:10:06.746 DEB iotile_transport_websocket.device_server Sending event broadcast: {'connection_string': 'adapter/0/None', 'serialized_report': {'origin': 3000, 'encoded_report': b'AwAQALgLAAAS+AQAAAAAACgQAAAAAAAAEvgEAMkCAAA=', 'report_format': 3, 'received_time': datetime.datetime(2019, 6, 7, 16, 9, 37, 853543)}}
```

Those report contents are identical so the throttling should have deduplicated them and not passed on the second one.  It looks like there's another bug or issue inside the bled112 throttling code that is preventing it from working.

**Comment by mattrunchey** [comment]
Ok, I realized that I applied the iotile setting to the wrong user account (I was on root instead of iotile). When I applied it to the proper user, it started functioning.

It actually did allow the iotile-gateway process to *barely* keep up, as opposed to falling catastrophically behind, but it seemed to be near its capacity. I didn't leave it running for very long but this is the first time I've seen its CPU drop to 24% instead of sticking at 25/6% .

**Comment by timburke** [comment]
Okay so it looks like we have further optimizations that need to be done inside `bled112.py` to handle high broadcast/scan packet volumes and reduce the load upstream but throttling there does help.
