### ISSUE TITLE
FlashBoardStep seems to fail. 

### ISSUE THREAD

**Issue by ekkizogloy** [iotile/coretools#884]
```
iotile-ship os2050_topboard.yaml
/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/ship/recipe.py:355: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  info = yaml.load(infile)
Running in .
===> Step 1: FlashBoardStep	 Description: Flash slot 4 (environmental)
Could not find core in Coresight setup
======> Time Elapsed: 3.79 seconds
Traceback (most recent call last):
  File "/Users/lukee/arch/env/py3/bin/iotile-ship", line 10, in <module>
    sys.exit(main())
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/ship/scripts/iotile_ship.py", line 99, in main
    recipe.run(variables)
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/ship/recipe.py", line 461, in run
    self._cleanup_resources(owned_resources)
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/ship/recipe.py", line 418, in _cleanup_resources
    raise RecipeResourceManagementError(operation="resource cleanup", errors=cleanup_errors)
TypeError: __init__() missing 1 required positional argument: 'msg'
Error running finalizer for task JLINK Adapter stopper
Traceback (most recent call last):
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/core/utilities/async_tools/event_loop.py", line 193, in stop
    await result
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile_transport_jlink/jlink.py", line 197, in stop
    await self.disconnect(self._connection_id)
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile_transport_jlink/jlink.py", line 313, in disconnect
    self._teardown_connection(conn_id)
  File "/Users/lukee/arch/env/py3/lib/python3.7/site-packages/iotile/core/hw/transport/adapter/mixin_conndata.py", line 62, in _teardown_connection
    raise DeviceAdapterError(conn_id, 'none', 'connection id torndown without being setup')
iotile.core.hw.exceptions.DeviceAdapterError: DeviceAdapterError: Operation none on conn 0 failed because connection id torndown without being setup
Additional Information:
reason: connection id torndown without being setup
operation: none
conn_id: 0
```

**Comment by x24ling** [comment]
What does your .yaml look like?
