### ISSUE TITLE
Intermittent test failures in `iotile_transport_bled112`

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#893]
In Azure pipelines, sometimes the OSX test environments seem to occasionally straight up hang on `iotile_transport_bled112`. I've seen it enough now that we might want to consider investigating this, as it's quite annoying to just rerun checks due to a timeout (it's still better than risking a buggy merge). 

```
  Running setup.py develop for iotile-ext-cloud
Successfully installed iotile-cloud-0.9.12 iotile-ext-cloud
Testing iotile_ext_cloud: PASSED (20.7 seconds)
Testing iotile_transport_awsiot: PASSED (1.3 seconds)
Testing iotile_transport_bled112: 
##[error]The operation was canceled.
```

A few reference links to the builds: 

https://dev.azure.com/iotile/coretools/_build/results?buildId=599
https://dev.azure.com/iotile/coretools/_build/results?buildId=656

Unfortunately, we don't see any test logs because Azure kills the container after 60 minutes.

I'm going to attempt to get a recreation on my machine, hopefully I can get us started on the actual test that's failing with more test output...

**Comment by mattrunchey** [comment]
I can't get these tests to fail so far on my machine when using the same base command (`pytest test -s` from within the `bled112` folder).

The only additional output I'm getting is some test cleanup failures. I'm going to see if I can't clean that up, but I doubt it's the reason we're hanging or it'd be more consistent.

```
Error running finalizer for task LegacyAdapter (BLED112Adapter)
Traceback (most recent call last):
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/utilities/async_tools/event_loop.py", line 193, in stop
    await result
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/transport/adapter/async_wrapper.py", line 103, in stop
    await self._execute(self._adapter.stop_sync)
  File "/usr/local/Cellar/python35/3.5.6_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/Cellar/python35/3.5.6_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/local/Cellar/python35/3.5.6_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/local/Cellar/python35/3.5.6_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/iotile_transport_bled112/bled112.py", line 174, in stop_sync
    self._serial_port.close()
  File "/Users/mrunchey/gitrepos/coretools/transport_plugins/bled112/test/util/dummy_serial.py", line 125, in close
    raise IOError('Dummy_serial: The port is already closed')
OSError: Dummy_serial: The port is already closed

```

**Comment by mattrunchey** [comment]
I've been playing with this on and off all night, and did some improvements on the test runner to get a timeout so they at least don't take an hour.

Unfortunately, what seems to happen is the subprocess running the tests just fails to stop. 

```
Here is some potential test output:  ============================= test session starts ==============================
platform darwin -- Python 3.5.7, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /Users/runner/runners/2.160.0/work/1/s/transport_plugins/bled112
plugins: iotile-cloud-0.9.12, localserver-0.5.0, requests-mock-1.7.0
collected 20 items

test/test_bled112_active.py ..
test/test_bled112_adapterstream.py ....
test/test_bled112_connecting.py .{UUID('0ff60f63-132c-e611-ba53-f73f00200000'): {'characteristics': {UUID('fb349b5f-8000-0080-0010-000000000320'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000320'), 'handle': 2, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=False, indicate=False, write_authenticated=False, extended=False)}, UUID('fb349b5f-8000-0080-0010-000000000120'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000120'), 'client_configuration': {'value': 0, 'handle': 7}, 'handle': 6, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=True, indicate=False, write_authenticated=False, extended=False)}, UUID('fb349b5f-8000-0080-0010-000000000220'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000220'), 'client_configuration': {'value': 0, 'handle': 10}, 'handle': 9, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=True, indicate=False, write_authenticated=False, extended=False)}, UUID('fb349b5f-8000-0080-0010-000000000420'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000420'), 'handle': 4, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=False, indicate=False, write_authenticated=False, extended=False)}, UUID('fb349b5f-8000-0080-0010-000000000520'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000520'), 'client_configuration': {'value': 0, 'handle': 13}, 'handle': 12, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=True, indicate=False, write_authenticated=False, extended=False)}, UUID('fb349b5f-8000-0080-0010-000000000620'): {'uuid': UUID('fb349b5f-8000-0080-0010-000000000620'), 'handle': 15, 'properties': CharacteristicProperties(broadcast=False, read=False, write_no_response=False, write=False, notify=False, indicate=False, write_authenticated=False, extended=False)}}, 'uuid_raw': UUID('0ff60f63-132c-e611-ba53-f73f00200000'), 'end_handle': 15, 'start_handle': 1}}
....
test/test_bled112_passive.py ..
test/test_bled112_reports.py ..
test/test_bled112_rpcs.py ..
test/test_loopback.py s
test/test_mockbled112.py ..

=============================== warnings summary ===============================
/Users/runner/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/typedargs/typeinfo.py:18
  /Users/runner/hostedtoolcache/Python/3.5.7/x64/lib/python3.5/site-packages/typedargs/typeinfo.py:18: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

/Users/runner/runners/2.160.0/work/1/s/iotilecore/iotile/core/utilities/packed.py:5
  /Users/runner/runners/2.160.0/work/1/s/iotilecore/iotile/core/utilities/packed.py:5: DeprecationWarning: unpack was a legacy shim for python < 2.7.5 and will be removed in a future iotile-core release
    warnings.warn("unpack was a legacy shim for python < 2.7.5 and will be removed in a future iotile-core release", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================== 19 passed, 1 skipped, 2 warnings in 44.16s ==================

FAILED (60.0 seconds)
```

**Comment by timburke** [comment]
@mattrunchey From reading through this, it sounds like you've done the hard work of tracing this to a shutdown failure of the pytest process.  Generally those are going to come from the existence of background threads that are not marked daemon and not properly shutdown.  The python interpreter will hang at exit with a `join` on all threads not marked daemon.

So, it could be there's a race condition somewhere that's causing a background thread in bled112 to stay around and that in turn is causing pytest to hang when it shuts down.

Putting a pytest session scope fixture that yields in the middle will give you an easy way to get code called right before shutdown (there's probably a hook somewhere in pytest's api as well for this).  You can enumerating the still running threads at that point to figure out what's going on:
https://stackoverflow.com/a/37942018/9739119

**Comment by mattrunchey** [comment]
Yea, seems like a likely culprit for sure. 

Unfortunately, I can't get a recreation on my machine after running it on a loop for an hour. 

So on the Azure agents, it doesn't seem trivial to inspect the running threads and print it between the end of the test run and before the process timeout. I could add another test whose job is to dump out the the running threads, which may give enough of a hint to latch on to. First attempt got at least something out, but it's going to be tough to track down what these threads are...

```
test/test_mockbled112.py ..<_MainThread(MainThread, started 140735841551232)>
MainThread
<Thread(Thread-8, started daemon 123145513963520)>
Thread-8
<Thread(Thread-9, started daemon 123145519218688)>
Thread-9
<Thread(Thread-13, started daemon 123145529729024)>
Thread-13
<Thread(EventLoopThread, started daemon 123145503453184)>
EventLoopThread
<Thread(Thread-22, started daemon 123145556004864)>
Thread-22
<Thread(Thread-23, started daemon 123145561260032)>
Thread-23
<Thread(Thread-19, started daemon 123145550749696)>
Thread-19
<Thread(Thread-14, started daemon 123145534984192)>
Thread-14
<Thread(Thread-18, started daemon 123145545494528)>
Thread-18
<Thread(Thread-7, started daemon 123145508708352)>
Thread-7
<Thread(Thread-24, started daemon 123145566515200)>
Thread-24
<Thread(Thread-12, started daemon 123145524473856)>
Thread-12
<Thread(Thread-17, started daemon 123145540239360)>
Thread-17
.
```

**Comment by timburke** [comment]
Hmm, it looks like some test is not cleaning up a background thread.  There shouldn't be that many alive at once.  I would expect maybe 3-5 total threads at most in a normal scenario.

In the past we've had issues where a test didn't clean up after itself and we had 1 background thread per test that just hung around forever.

In terms of injecting the logging code to fun after the tests, you can just make a session scoped fixture that is marked as autouse and put a yield statement inside:

```python
import pytest

@pytest.fixture(scope='session', autouse=True)
def logging_fixture():
    # Runs before all tests
    yield

    # Runs after all tests
    # Enumerate running threads here
```

**Comment by mattrunchey** [comment]
With more testing, I believe the culprit is in the `test_bled112_adapterstream` setup/teardown.

I marked the entire file as skipped. Then, each of the test suites showed a more normal number of threads (two). For each test I uncommented in `test_bled112_adapterstream`, I got 3 new threads that never ended. 

One hint is that we are hitting an exception in `stop_sync` from `bled112.py` on line 174 -- https://github.com/iotile/coretools/blob/a4511876381f6c0566460181067a9c47ae42a828/transport_plugins/bled112/iotile_transport_bled112/bled112.py#L174 :
```
self._serial_port.close()
```

However, handling this `IOError` exception only keeps us from having some error output -- it doesn't do enough to kill the thread, so something else in that object (or an object that's using it) is alive. 

The other tests have a nearly identical set up to this file. The key difference is that in the setUp, we are creating a HardwareManager : 
```
        self.hw = HardwareManager(port='bled112:test')
```

and the tests are calling `connect_direct`. 

Think I'm getting close.
