### ISSUE TITLE
Missing Crypto dependency for iotile.core

### ISSUE THREAD

**Issue by lelithium** [iotile/coretools#919]
Steps to replicate:
```
python3 --version
Python 3.7.3

python3 -m venv venv
. venv/bin/activate
pip install iotile-core
python -c "import iotile.core.hw"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/__init__.py", line 2, in <module>
    from .proxy import TileBusProxyObject
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/proxy/__init__.py", line 9, in <module>
    from .proxy import TileBusProxyObject
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/proxy/proxy.py", line 15, in <module>
    from ..virtual import pack_rpc_payload, unpack_rpc_payload
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/virtual/__init__.py", line 119, in <module>
    from .virtualdevice_base import BaseVirtualDevice, AbstractAsyncDeviceChannel
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/virtual/virtualdevice_base.py", line 9, in <module>
    from ..reports.individual_format import IndividualReadingReport
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/reports/__init__.py", line 3, in <module>
    from .signed_list_format import SignedListReport
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/reports/signed_list_format.py", line 10, in <module>
    from iotile.core.hw.auth.auth_provider import AuthProvider
  File "[...]/venv/lib/python3.7/site-packages/iotile/core/hw/auth/auth_provider.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

This differs from the expected behavior, stated [here](https://github.com/iotile/coretools#working-with-encrypted-device-data), that `pycrypto` is only required for working with encrypted data.

The issue was introduced during PR #879. It was not flagged in the tests due to `pycryptodome` being installed manually in the `tox.ini` file.

**Proposed fix**: Add `pycryptodome` to the `setup.py` file for `iotile-core`. `pycrypto` is unmaintained, and `pycryptodome` offers a drop-in replacement (see [this article](https://blog.sqreen.com/stop-using-pycrypto-use-pycryptodome/))

**Comment by lelithium** [comment]
@DimaWittmann @mattrunchey for visibility

**Comment by timburke** [comment]
@DimaWittmann We need to restore the old behavior where `iotile-core` only imported `Crypto` if it was asked to perform an operation that needs it.  This was the behavior before in, e.g. the old `EnvAuthProvider` that had the `Crypto` imports inside the methods that used them and had the methods fail if Crypto was not found.

There are a lot of places that `iotile-core` is used for its `report` generation features that don't need the large extra crypto dependency and historically haven't had it.

This is high priority to fix in `iotile-core` and release a patch update since the current public release is now broken.

**Comment by timburke** [comment]
@lelithium You can blacklist `iotile-core == 5.0.10` to work around this and unblock until we release an updated version resolving the issue.

**Comment by mattrunchey** [comment]
https://github.com/iotile/coretools/issues/847 talks a bit about this as well

**Comment by DimaWittmann** [comment]
Fixed in coretools 5.0.11

**Comment by mattrunchey** [comment]
@DimaWittmann FYI 5.0.11 did not get released yet, but the tag is in.

To complete the release process after submitting a PR to master, you need to create the tag `iotilecore-5.0.11` (https://github.com/iotile/coretools#continuous-deployment) .

You can do this by pushing a tag via the command line, or you can "Draft a new Release" and put in the package-version combo as above: https://github.com/iotile/coretools/releases 

Let me know if you aren't able to do this, but I believe we set the permissions up such that anyone on a contributor team can also cut a release.

**Comment by DimaWittmann** [comment]
@mattrunchey Thank you, I pushed the tag

**Comment by timothyfroehlich** [comment]
This doesn't appear to be fully fixed. I'm having iotile-gateway problems trying to import iotile-transport-bled112.

```Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: 20-01-07 23:59:48.768 CRI iotilegateway.main Starting gateway
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: 20-01-07 23:59:48.937 WAR iotile.core.dev.registry Unable to load bled112 from Distribution('iotile_transport_bled112', '3.0.2-py3.7')
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: Traceback (most recent call last):
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotile/core/dev/registry.py", line 167, in load_extensions
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     ext = entry.load()
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/entrypoints.py", line 82, in load
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     mod = import_module(self.module_name)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotile_transport_bled112/bled112.py", line 13, in <module>
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     from Crypto.Cipher import AES
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: ModuleNotFoundError: No module named 'Crypto'
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: 20-01-07 23:59:48.946 ERR iotilegateway.gateway Could not load device adapter bled112
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: Traceback (most recent call last):
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotilegateway/gateway.py", line 121, in _load_adapters
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     _, adapter_class = reg.load_extensions('iotile.device_adapter', name_filter=adapter_name, unique=True)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotile/core/dev/registry.py", line 186, in load_extensions
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     raise ArgumentError("Extension %s had no instances of class %s" % (group, class_filter.__name__))
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: AttributeError: 'NoneType' object has no attribute '__name__'
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: 20-01-07 23:59:48.949 ERR iotilegateway.main Fatal error running gateway
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: Traceback (most recent call last):
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotilegateway/main.py", line 84, in main
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     gateway = IOTileGateway(args, loop=loop)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotilegateway/gateway.py", line 45, in __init__
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     self.adapters = _load_adapters(self._config.get('adapters', []), self._loop, self._logger)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotilegateway/gateway.py", line 121, in _load_adapters
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     _, adapter_class = reg.load_extensions('iotile.device_adapter', name_filter=adapter_name, unique=True)
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:   File "/usr/lib/python3.7/site-packages/iotile/core/dev/registry.py", line 186, in load_extensions
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]:     raise ArgumentError("Extension %s had no instances of class %s" % (group, class_filter.__name__))
Jan 07 23:59:48 raspberrypi3 iotile-gateway[450]: AttributeError: 'NoneType' object has no attribute '__name__'
Jan 07 23:59:49 raspberrypi3 systemd[1]: iotile-gateway.service: Main process exited, code=exited, status=1/FAILURE
Jan 07 23:59:49 raspberrypi3 systemd[1]: iotile-gateway.service: Failed with result 'exit-code'.```

The error is being raised and not caught, causing iotile-gateway to crash.

Here are my iotile package versions:
```iotile-cloud                    0.9.12   
iotile-core                     5.0.11   
iotile-ext-cloud                1.0.10   
iotile-gateway                  3.0.1    
iotile-support-con-nrf52832-3   3.2.4    
iotile-support-lib-controller-3 3.8.2    
iotile-transport-bled112        3.0.2    
iotile-transport-socket-lib     1.0.0    
iotile-transport-websocket      3.1.0```

**Comment by mattrunchey** [comment]
Ah. We changed the code in the `bled112` plugin but neglected to also release an update to it. Fix is to update version.py and RELEASE.MD for the bled112 plugin.
