### ISSUE TITLE
CRCmod module missing from Coretools dependencies

### ISSUE THREAD

**Issue by timothyfroehlich** [iotile/coretools#992]
In tox tests for another package, I started getting this recently:
```
----------------------------- Captured stderr call -----------------------------
WARNING:iotile.core.dev.registry:Unable to load sensorgraph from Distribution('iotile_support_lib_controller_3', '3.8.5')
Traceback (most recent call last):
  File "/var/app/.tox/py/lib/python3.6/site-packages/iotile/core/dev/registry.py", line 167, in load_extensions
    ext = entry.load()
  File "/var/app/.tox/py/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/app/.tox/py/lib/python3.6/site-packages/iotile_support_lib_controller_3/sensorgraph.py", line 7, in <module>
    from iotile.core.utilities.hash_algorithms import KNOWN_HASH_ALGORITHMS
  File "/var/app/.tox/py/lib/python3.6/site-packages/iotile/core/utilities/hash_algorithms/__init__.py", line 4, in <module>
    from .crc import calculate_crc
  File "/var/app/.tox/py/lib/python3.6/site-packages/iotile/core/utilities/hash_algorithms/crc.py", line 1, in <module>
    import crcmod
ModuleNotFoundError: No module named 'crcmod'
------------------------------ Captured log call -------------------------------
WARNING  iotile.core.dev.registry:registry.py:169 Unable to load sensorgraph from Distribution('iotile_support_lib_controller_3', '3.8.5')
Traceback (most recent call last):
  File "/var/app/.tox/py/lib/python3.6/site-packages/iotile/core/dev/registry.py", line 167, in load_extensions
    ext = entry.load()
  File "/var/app/.tox/py/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
```

It seems that Coretools now has a dependency on the `crcmod` package, but it's not listed in it's dependencies, which caused the tox failure.

I'm not sure which version of `crcmod` it should be pegged to. @anwu Do you know?

**Comment by anwu** [comment]
Ahh that was part of my sensorgraph hashing effort. I thought I had included that, my bad.

I believe `crcmod-1.7` should be good.
